
config:
  image:
    repository: positionpal/location-service
    tag: latest
    pullPolicy: IfNotPresent

  servicename: locservice
  replicaNumber: 2
  requiredContactPointNr: 2

  managementPort: 8558
  httpPort: 8080
  grpcPort: 5052

  mapboxApi: ""

  akka:
    licenseKey: ""

# Configure the connection information for the rabbtimq service
rabbitmq:
  username: user
  password: 3P76p1ODAfi4R2WO
  namespace: rabbitmq
  serviceName: rabbitmq
  virtualHost: /
  port: 5672

# Configure the connection information for the cassandra service
cassandra:

  image:
    debug: true
 
  dbUser:
    user: admin
    password: password

  replicaCount: 2
  initDBConfigMap: script-db-configmap
