
# Configure the connection information for the rabbtimq service
rabbitmq:
  username: user
  password: GJthvthGh5bfn9dG
  namespace: rabbitmq
  serviceName: rabbitmq
  port: 5672

# Configure the connection information for the cassandra service
cassandra:

  image:
    debug: true
 
  dbUser:
    user: admin
    password: password

  replicaCount: 3

  initDBConfigMap: script-db-configmap
  
  resources:
    requests:
      memory: 4Gi
      cpu: 2
    limits:
      memory: 8Gi
      cpu: 4